### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by Prospero1** [Frankenmint/PKGenerator_Checker#3]
Was working for a while.

Traceback (most recent call last):
  File "PkMaker.py", line 82, in <module>
    ping_address(publicAddress)
  File "PkMaker.py", line 40, in ping_address
    balance = pmts['balance']
KeyError: 'balance'

After couple of minutes it cannot run becouse of keyerror.

Any reason ?

**Comment by Frankenmint** [comment]
yeah... the JSON returned is either saying something abou rate limiting or returning with a different status such as 503 since you're essentially sending reuest after request to it.  That can sometimes happen if you're pointed to the same block explorer for a while, it will eventually block you and/or set rate-limiting.  To get around this you'll either want to point to different block explorers or you'll need to throttle how often you us the script.  Simple turn it off for a little while then turn it back on again and it should begin working.

I propose this long term fix:

1. we could do a try: except: on the keyError and have it do a small bit of a cooldown whenever an explorer API blocks us.
2. we could build in more block explorers so that the script is only making calls maybe  1 every 3 seconds.. this way we don't trigger rate limiting. 

sort of tied up for time these days but I'll likely put something together in a few days for ya

**Comment by Frankenmint** [comment]
I found a block exporer that claims to have no limit so implementing that in addition to implementing the 1st solution rather than pointing to multiple block explorers.

4209b34b7799567e11a6e32c3569c8861294f44b

Seems to work fine for me but let us know - I'm thinking to maybe add in a printout of the request so it shows in the window itself
