### ISSUE TITLE
Running in the background

### ISSUE THREAD

**Issue by Darkstar91** [Frankenmint/PKGenerator_Checker#4]
Hello i have a root Server..would it be possible? to run the program in the background(rc.local) and if the script find a adress with bitcoin Balance to give them to a .log file with the bitcoin adress, private Key and the balance.

**Comment by Frankenmint** [comment]
it currently logs all keys by defualt so if one is discovered it will be in a log somewhere.  the v2 version of the script has a small smtp mechanism in it so you can have it send email when a pk is found... you could copy the smtp from the v2 into the v1 mechanism so that you get an email with a key that's found.... for the sake of ease, I've decided to copy the logging mechanism into line 48 in case a PK that has a balance IS found... just comment out line 46 to not record blank keys - though in the future they may be populated so I say to record any and every generated private key if you can.
